apiVersion: apps/v1
kind: Deployment
metadata:
  name: qweelvo-mini-app
  namespace: core
spec:
  replicas: 2
  selector:
    matchLabels:
      app: qweelvo-mini-app
  template:
    metadata:
      labels:
        app: qweelvo-mini-app
    spec:
      serviceAccountName: qweelvo-mini-app-sa
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: qweelvo-mini-app
          image: ghcr.io/youssefalaa10/qweelvo-mini-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 3
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 3
