apiVersion: apps/v1
kind: Deployment
metadata:
  name: qweelvo-mini-app
  namespace: core
spec:
  replicas: 2
  selector:
    matchLabels:
      app: qweelvo-mini-app
  template:
    metadata:
      labels:
        app: qweelvo-mini-app
    spec:
      containers:
        - name: qweelvo-mini-app
          image: ghcr.io/youssefalaa10/qweelvo-mini-app:sha-30c2c14
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /
              port: 8000
          livenessProbe:
            httpGet:
              path: /
              port: 8000